version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "6085e2412b6fa88647466c6a81c0cea0"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    
    ports:
    - "15672:15672"
    - "5672:5672" 
